<!-- Footer -->

 <div id="bottom">
	<p style="margin:0;">Copyright &copy; Justin Phelps, 2008. <a href="http://www.w3.org/TR/xhtml1/" target="_blank">Valid XHTML</a>, <a href="http://www.w3.org/Style/CSS/" target="_blank">Valid CSS</a></p>
 </div>
 
<!-- End Footer -->

<!-- Google Analytics -->
<script type="text/javascript">var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www."); document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));</script>
<script type="text/javascript">var pageTracker = _gat._getTracker(""); pageTracker._initData(); pageTracker._trackPageview();</script>

</body>
</html>
