<!-- Navigation -->
 
 <div id="nav">
	<a href="index.php">Home</a>
	<a href="calendar.php">Calendar</a>
	<a href="registry.php">Registry</a> 
	<a href="https://www.dropbox.com/gallery/13160/1/Wedding%20Photos?h=d4b1af" target="_blank">Gallery</a>
	<a href="news.php">News</a> 
	<a href="contact.php">Contact</a>
	<a href="downloads.php">Downloads</a>
 </div>
 
<!-- End Navigation -->

<!-- Countdown Timer -->
<!--<br /><center>
<script type="text/JavaScript">countdown_clock(08, 5, 17, 15, 00, 1); </script>
</center>-->

