<!-- News Box -->

 <div id="left">
	 <div id="info">
		<p class="news1">News</p>
		
		<!--<p><a href="news.php#news3"><strong>RSVP Today!</strong></a></p>
		<p><a href="calendar.php">Calendar of Events</a></p>-->
	 </div>
	<p class="box">
	<strong><a href="news.php#news15">1.25.2009</a></strong><br />Site restored from backup<br />
	<strong><a href="news.php#news14">7.29.2008</a></strong><br />Support the HEART WALK<br />
	<strong><a href="news.php#news13">6.4.2008</a></strong><br />Lots of Photos<br />
	<strong><a href="news.php#news12">5.25.2008</a></strong><br />15 Minutes of Fame<br />
	<strong><a href="news.php#news11">5.8.2008</a></strong><br />All jokes aside . . .<br />
	<strong><a href="news.php#news10">4.1.2008</a></strong><br />Bundle of Joy!<br />
	<strong><a href="news.php#news9">3.31.2008</a></strong><br />Countdown Timer<br />
	<!--<strong><a href="news.php#news8">3.15.2008</a></strong><br />Wedding Shower<br />-->
	<!--<strong><a href="news.php#news7">2.20.2008</a></strong><br />New Server and AMV<br />-->
	<!--<strong><a href="news.php#news6">2.10.2008</a></strong><br />New Pictures and Comment System<br />-->
	<!--<strong><a href="news.php#news5">2.8.2008</a></strong><br />So much to do, so little time . . .<br />-->
	<!--<strong><a href="news.php#news4">2.5.2008</a></strong><br />We've added tunes and graphics. Check it out :)<br />-->
	<!--<strong><a href="news.php#news3">2.4.2008</a></strong><br />The invitations have been mailed and our RSVP is now active on the site.<br />-->
	<!--<strong><a href="news.php#news2">1.28.2008</a></strong><br />We have made many updates to the website. Please have a look around.<br />-->
	<!--<strong><a href="news.php#news1">12.18.2007</a></strong><br />Welcome to the development site for Justin and Savana. Stay tuned for updates.<br /><a href="news.php">News Archive</a>-->
 </div> 
 
<!-- End News Box -->

