<!-- Gallery -->

 <div id="galleryhold">
	<!--<p class="news">Images from the gallery</p>-->
	<!--<p align="center">Pictures coming soon . . . </p>-->
	<!--<span class="gallerybox"><a href="#"><img src="img/thumbnail.jpg" width="50" height="50" alt="Thumbnail Example" /></a></span>
	<span class="gallerybox"><a href="#"><img src="img/swing.jpg" width="50" height="50" alt="Thumbnail Example" /></a></span>
	<span class="gallerybox"><a href="#"><img src="img/thumbnail.jpg" width="50" height="50" alt="Thumbnail Example" /></a></span>
	<span class="gallerybox"><a href="#"><img src="img/thumbnail.jpg" width="50" height="50" alt="Thumbnail Example" /></a></span>
	<span class="gallerybox"><a href="#"><img src="img/swing.jpg" width="50" height="50" alt="Thumbnail Example" /></a></span>
	<span class="gallerybox"><a href="#"><img src="img/thumbnail.jpg" width="50" height="50" alt="Thumbnail Example" /></a></span>-->

<!-- End Gallery -->

